-- M1: workspace 隔离 + 初筛数据对象（assessment/contact_events/api_cache）+ 任务约束
-- 范围: 单操作者本地演示。DB 级多租户 RLS 加固属 P2（见 PRD v0.2 §6）。
-- 隔离执行点: 数据访问层(workbenchApi)始终按 workspace_id 过滤；表上保留 authenticated 基础策略，与上游模式一致。

-- ============ 1. workspace ============
create table if not exists "public"."workspace" (
    "id" bigint generated by default as identity primary key,
    "sales_id" bigint not null references public.sales(id),
    "mode" text not null check (mode in ('real', 'demo')),
    "product" text,
    "scene" text,
    "market" text,
    "brief_version" int not null default 1,
    "created_at" timestamptz not null default now(),
    unique (sales_id, mode)
);
alter table "public"."workspace" enable row level security;
create policy "workspace_all_authenticated" on "public"."workspace"
  for all to authenticated using (true) with check (true);

-- 为每个已有销售建 real/demo 双空间
insert into public.workspace (sales_id, mode)
  select s.id, 'real' from public.sales s
  where not exists (select 1 from public.workspace w where w.sales_id = s.id and w.mode = 'real');
insert into public.workspace (sales_id, mode)
  select s.id, 'demo' from public.sales s
  where not exists (select 1 from public.workspace w where w.sales_id = s.id and w.mode = 'demo');

-- ============ 2. contacts 挂到 workspace ============
alter table "public"."contacts"
  add column if not exists "workspace_id" bigint references public.workspace(id),
  add column if not exists "do_not_contact" boolean not null default false,
  add column if not exists "do_not_contact_reason" text,
  add column if not exists "do_not_contact_at" timestamptz;

-- 存量联系人都归到其 sales 的 real 空间
update public.contacts co
  set workspace_id = w.id
  from public.workspace w
  where w.sales_id = co.sales_id and w.mode = 'real'
    and co.workspace_id is null;

-- 频道唯一性从全局升级为 workspace 级
drop index if exists contacts_channel_id_uniq;
create unique index if not exists contacts_workspace_channel_uniq
  on public.contacts (workspace_id, channel_id) where channel_id is not null;

-- ============ 3. assessment 判断卡（版本追加式） ============
create table if not exists "public"."assessment" (
    "id" bigint generated by default as identity primary key,
    "candidate_id" bigint not null references public.contacts(id) on delete cascade,
    "workspace_id" bigint not null references public.workspace(id),
    "scene_fit" text not null default 'unknown' check (scene_fit in ('yes','no','unknown')),
    "entity_fit" text not null default 'unknown' check (entity_fit in ('yes','no','unknown')),
    "audience_evidence" text not null default 'unknown' check (audience_evidence in ('yes','no','unknown')),
    "content_scale_fit" text not null default 'unknown' check (content_scale_fit in ('yes','no','unknown')),
    "category_experience" text not null default 'unknown' check (category_experience in ('yes','no','unknown')),
    "decision" text not null check (decision in ('priority_contact','needs_info','paused')),
    "reason" text not null,
    "evidence" text,
    "open_questions" text,
    "brief_version" int not null default 1,
    "data_version" int,
    "created_at" timestamptz not null default now()
);
alter table "public"."assessment" enable row level security;
create policy "assessment_all_authenticated" on "public"."assessment"
  for all to authenticated using (true) with check (true);
create index if not exists assessment_candidate_idx on public.assessment (candidate_id, created_at desc);

-- ============ 4. contact_events 联系事件（sent/replied，可撤销） ============
create table if not exists "public"."contact_events" (
    "id" bigint generated by default as identity primary key,
    "candidate_id" bigint not null references public.contacts(id) on delete cascade,
    "workspace_id" bigint not null references public.workspace(id),
    "type" text not null check (type in ('sent', 'replied')),
    "occurred_at" timestamptz not null,
    "note" text,
    "voided_at" timestamptz
);
alter table "public"."contact_events" enable row level security;
create policy "contact_events_all_authenticated" on "public"."contact_events"
  for all to authenticated using (true) with check (true);
create index if not exists contact_events_candidate_idx on public.contact_events (candidate_id, occurred_at desc);

-- ============ 5. api_cache 外部数据快照（与业务记录分表，30 天生命周期） ============
create table if not exists "public"."api_cache" (
    "id" bigint generated by default as identity primary key,
    "candidate_id" bigint not null references public.contacts(id) on delete cascade,
    "workspace_id" bigint not null references public.workspace(id),
    "kind" text not null check (kind in ('channel', 'video')),
    "raw" jsonb not null,
    "source" text not null default 'synthetic',
    "fetched_at" timestamptz not null default now(),
    "expires_at" timestamptz not null default (now() + interval '30 days')
);
alter table "public"."api_cache" enable row level security;
create policy "api_cache_all_authenticated" on "public"."api_cache"
  for all to authenticated using (true) with check (true);
create index if not exists api_cache_candidate_idx on public.api_cache (candidate_id);

-- ============ 6. tasks 增强取消语义 + 单 open 约束 ============
alter table "public"."tasks"
  add column if not exists "cancelled_at" timestamptz,
  add column if not exists "cancel_reason" text;

create unique index if not exists tasks_one_open_per_contact
  on public.tasks (contact_id)
  where done_date is null and cancelled_at is null;

-- ============ 7. save_assessment RPC（评估版本追加 + 任务替换，单事务） ============
create or replace function public.save_assessment(
    p_candidate_id bigint,
    p_workspace_id bigint,
    p_scene_fit text,
    p_entity_fit text,
    p_audience_evidence text,
    p_content_scale_fit text,
    p_category_experience text,
    p_decision text,
    p_reason text,
    p_evidence text,
    p_open_questions text,
    p_brief_version int,
    p_data_version int,
    p_task_type text,
    p_task_due date
) returns bigint
language plpgsql
as $$
declare
    v_assessment_id bigint;
    v_is_dnc boolean;
begin
    -- 候选归属校验
    select (do_not_contact) into v_is_dnc
      from public.contacts where id = p_candidate_id and workspace_id = p_workspace_id;
    if v_is_dnc is null then
        raise exception 'candidate % not found in workspace %', p_candidate_id, p_workspace_id;
    end if;

    -- 按结论校验必填（PRD F3）
    if p_decision = 'priority_contact' then
        if v_is_dnc then raise exception 'candidate is marked do_not_contact'; end if;
        if p_reason is null or btrim(p_reason) = ''
           or p_evidence is null or btrim(p_evidence) = ''
           or p_scene_fit is distinct from 'yes'
           or p_task_type is null or p_task_due is null then
            raise exception 'priority_contact requires reason, evidence, scene_fit=yes, next task';
        end if;
    elsif p_decision = 'needs_info' then
        if v_is_dnc then raise exception 'candidate is marked do_not_contact'; end if;
        if p_open_questions is null or btrim(p_open_questions) = ''
           or p_task_type is null or p_task_due is null then
            raise exception 'needs_info requires open question and next task';
        end if;
    elsif p_decision = 'paused' then
        if p_reason is null or btrim(p_reason) = '' then
            raise exception 'paused requires reason';
        end if;
    else
        raise exception 'invalid decision %', p_decision;
    end if;

    -- 关闭原有 open 任务（取消，记录原因）
    update public.tasks
       set cancelled_at = now(),
           cancel_reason = 'replaced by new assessment (' || p_decision || ')'
     where contact_id = p_candidate_id
       and done_date is null and cancelled_at is null;

    -- 追加判断版本
    insert into public.assessment
        (candidate_id, workspace_id, scene_fit, entity_fit, audience_evidence,
         content_scale_fit, category_experience, decision, reason, evidence,
         open_questions, brief_version, data_version)
    values
        (p_candidate_id, p_workspace_id, p_scene_fit, p_entity_fit, p_audience_evidence,
         p_content_scale_fit, p_category_experience, p_decision, p_reason, p_evidence,
         p_open_questions, p_brief_version, p_data_version)
    returning id into v_assessment_id;

    -- 创建新 open 任务（暂缓不建任务；停止联系仅允许 review）
    if p_task_type is not null and p_task_due is not null then
        if v_is_dnc and p_task_type in ('first_contact', 'follow_up') then
            raise exception 'cannot create contact task for do_not_contact candidate';
        end if;
        insert into public.tasks (contact_id, type, text, due_date)
        values (p_candidate_id, p_task_type, coalesce(p_reason, ''), p_task_due::timestamptz);
    end if;

    return v_assessment_id;
end;
$$;
